version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ../../
      dockerfile: deployments/development/Dockerfile
    ports:
      - 8081:${APPLICATION_PORT}
    env_file:
      - .env.example
    environment:
      - LDFLAGS=${LDFLAGS}
