version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ../../
      dockerfile: deployments/development/Dockerfile
    ports:
      - 8081:${APPLICATION_PORT}
    volumes: # CompileDaemon doesn't work without it
      - ../../:/app
    env_file:
      - .env
